### ISSUE TITLE
Failure after 4 entries

### ISSUE THREAD

**Issue by asorel1942** [opravdin/yandex-browser-password-export#2]
I had to change the number of tab sends from 18 to 20. After that, the script seems to work fine for the first 4 passwords listed, then stops. It pastes the password of entry #4 for two lines, then switches to the add-ons screen in the browser.

**Comment by opravdin** [comment]
This thing is very system-dependent. IMO this issue caused by instability in system perfomance (and, in general, difference between systems at all). Try to adjust delays between key sends (x2-4 for example) and add additional ones (50-100) between key sendings (especially after alt-tabs). I have some reports in youtube comments that this could solve issue. 
Btw if you succeed in this, please write your experience here or make pull request with adjusted delays (I think it will be reasonable) or recomendations in readme. I can't do it by myself because this version still works pretty good on my system (with 20 tabs and with that delay values)

**Comment by asorel1942** [comment]
I tried doubling the delays, and it worked fine out to ~350 entries or so, at which point I started getting a similar issue to before. Stopped and started again and it continued without a hitch, so I assume it was just a fluke. If you like, once I figure out how I can upload my modified version.

**Comment by opravdin** [comment]
You should fork this repository, commit and push updated version and then make pull request to this repo. Or I will do everything by myself: just send me updated version on email "opravdin at gmail dot com"
Glad to help you :)
